### ISSUE TITLE
Problem in sending a message using my google account

### ISSUE THREAD

**Issue by liuzheng1990** [Weizhang2017/SMTPEmail#1]
Hi. I like this small but handy mail management wrapper. I had a problem in sending message using the SMTP class, though, using my Google account. I got `socket.gaierror: [Errno 8] nodename nor servname provided, or not known` error. Here are some details (I have turned on the `less secure app` option in google account.)

```python
>>> from SMTPEmail import SMTP
>>> client = SMTP(SMTP_server="smtp.google.com", SMTP_account=<my account>, SMTP_password=<my password>)
>>>
>>> client.create_mime(recipient_email_addr=<another email address of mine>, 
               sender_email_addr='<my sending email address>', 
               subject='hello!', 
               sender_display_name='myself', 
               content_text='A greet from my own local machine!')
<email.message.EmailMessage object at 0x103675518>
>>>
>>>
>>> print(client)
Subject: hello!
From: myself <sending email address>
To: <another email address of mine>
Date: Wed, 21 Nov 2018 11:15:13 +0800
Message-Id: <some long number>@gmail.com
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
MIME-Version: 1.0

A greet from my own local machine!

>>> client.send_msg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/SMTPEmail/SMTPEmail.py", line 97, in send_msg
    with smtplib.SMTP(self.SMTP_server, self.port) as server:
  File "/anaconda3/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/anaconda3/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/anaconda3/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/anaconda3/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Seems there is a problem about the underlying socket. Any idea what caused this problem?

Cheers

**Comment by Weizhang2017** [comment]
The SMTP server domain is incorrect. For gmail SMTP server, the domain is  "smtp.gmail.com".

**Comment by liuzheng1990** [comment]
Ah. My bad. Thanks
